import { Inter } from "next/font/google";
import Bootstrap from "./components/Bootstrap.js";
import '/node_modules/bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Botanic Basket",
    template: "%s - Botanic Basket",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Bootstrap />
      </body>
    </html>
  );
}
